/**
 * model_inference.c -- ML model inference for PwnAUI Pi brain
 *
 * Pure int8 arithmetic with float only at final dequantization.
 * All inference runs in <1ms on ARMv6 (Pi Zero W).
 *
 * Uses weights from model_weights.h (auto-generated by PC Brain).
 */

#include "model_inference.h"
#include "model_weights.h"
#include <math.h>
#include <string.h>
#include <time.h>

/* ---- Helpers ---- */

static inline float relu_f(float x) {
    return x > 0.0f ? x : 0.0f;
}

static inline float sigmoid_f(float x) {
    if (x > 20.0f) return 1.0f;
    if (x < -20.0f) return 0.0f;
    return 1.0f / (1.0f + expf(-x));
}

static inline float clamp_f(float x, float lo, float hi) {
    if (x < lo) return lo;
    if (x > hi) return hi;
    return x;
}

/* Softmax in-place over n elements */
static void softmax_inplace(float *x, int n) {
    float max_val = x[0];
    for (int i = 1; i < n; i++) {
        if (x[i] > max_val) max_val = x[i];
    }
    float sum = 0.0f;
    for (int i = 0; i < n; i++) {
        x[i] = expf(x[i] - max_val);
        sum += x[i];
    }
    if (sum > 0.0f) {
        for (int i = 0; i < n; i++) {
            x[i] /= sum;
        }
    }
}

/* Argmax over n elements */
static int argmax(const float *x, int n) {
    int best = 0;
    for (int i = 1; i < n; i++) {
        if (x[i] > x[best]) best = i;
    }
    return best;
}


/* ---- Init ---- */

void model_inference_init(void) {
    /* Nothing to allocate -- all weights are static const.
     * This function exists for future extensibility
     * (e.g., loading weights from file instead of compiled-in). */
}


/* ---- Model 1: AP Vulnerability Predictor ---- */

float predict_vulnerability(const ap_features_t *ap) {
#if VULN_AVAILABLE
    float input[VULN_N_FEATURES] = {
        ap->vendor_category,
        ap->encryption_type,
        ap->channel_norm,
        ap->beacon_flag,
        ap->client_count_log,
        ap->rssi_norm,
        ap->time_of_day,
    };

    /* Layer 1: input -> hidden1 (ReLU) */
    float h1[VULN_HIDDEN1];
    for (int j = 0; j < VULN_HIDDEN1; j++) {
        float acc = (float)vuln_b1[j] * vuln_scale_b1;
        for (int i = 0; i < VULN_N_FEATURES; i++) {
            acc += input[i] * (float)vuln_w1[i][j] * vuln_scale_w1;
        }
        h1[j] = relu_f(acc);
    }

    /* Layer 2: hidden1 -> hidden2 (ReLU) */
    float h2[VULN_HIDDEN2];
    for (int j = 0; j < VULN_HIDDEN2; j++) {
        float acc = (float)vuln_b2[j] * vuln_scale_b2;
        for (int i = 0; i < VULN_HIDDEN1; i++) {
            acc += h1[i] * (float)vuln_w2[i][j] * vuln_scale_w2;
        }
        h2[j] = relu_f(acc);
    }

    /* Layer 3: hidden2 -> output (Sigmoid) */
    float out = (float)vuln_b3[0] * vuln_scale_b3;
    for (int i = 0; i < VULN_HIDDEN2; i++) {
        out += h2[i] * (float)vuln_w3[i][0] * vuln_scale_w3;
    }

    return sigmoid_f(out);
#else
    (void)ap;
    return 0.5f; /* neutral prediction */
#endif
}


/* ---- Model 2: Attack Phase Selector ---- */

int predict_attack_phase(const ap_features_ext_t *ap) {
#if PHASE_AVAILABLE
    float input[PHASE_N_FEATURES] = {
        ap->base.vendor_category,
        ap->base.encryption_type,
        ap->base.channel_norm,
        ap->base.beacon_flag,
        ap->base.client_count_log,
        ap->base.rssi_norm,
        ap->base.time_of_day,
        ap->thompson_ratio,
        ap->has_pmkid,
        ap->is_wpa3,
    };

    /* Layer 1 */
    float h1[PHASE_HIDDEN1];
    for (int j = 0; j < PHASE_HIDDEN1; j++) {
        float acc = (float)phase_b1[j] * phase_scale_b1;
        for (int i = 0; i < PHASE_N_FEATURES; i++) {
            acc += input[i] * (float)phase_w1[i][j] * phase_scale_w1;
        }
        h1[j] = relu_f(acc);
    }

    /* Layer 2 */
    float h2[PHASE_HIDDEN2];
    for (int j = 0; j < PHASE_HIDDEN2; j++) {
        float acc = (float)phase_b2[j] * phase_scale_b2;
        for (int i = 0; i < PHASE_HIDDEN1; i++) {
            acc += h1[i] * (float)phase_w2[i][j] * phase_scale_w2;
        }
        h2[j] = relu_f(acc);
    }

    /* Layer 3: softmax */
    float out[PHASE_OUTPUT];
    for (int j = 0; j < PHASE_OUTPUT; j++) {
        out[j] = (float)phase_b3[j] * phase_scale_b3;
        for (int i = 0; i < PHASE_HIDDEN2; i++) {
            out[j] += h2[i] * (float)phase_w3[i][j] * phase_scale_w3;
        }
    }
    softmax_inplace(out, PHASE_OUTPUT);

    return argmax(out, PHASE_OUTPUT);
#else
    (void)ap;
    return -1;
#endif
}


/* ---- Model 3: Channel Yield Predictor ---- */

int predict_channel_yield(const channel_query_t *query, float yield[14]) {
#if CHAN_AVAILABLE
    float input[CHAN_N_FEATURES] = {
        query->time_of_day,
        query->gps_zone,
        query->day_of_week,
    };

    /* Layer 1 */
    float h1[CHAN_HIDDEN1];
    for (int j = 0; j < CHAN_HIDDEN1; j++) {
        float acc = (float)chan_b1[j] * chan_scale_b1;
        for (int i = 0; i < CHAN_N_FEATURES; i++) {
            acc += input[i] * (float)chan_w1[i][j] * chan_scale_w1;
        }
        h1[j] = relu_f(acc);
    }

    /* Layer 2: softmax distribution */
    for (int j = 0; j < CHAN_OUTPUT; j++) {
        yield[j] = (float)chan_b2[j] * chan_scale_b2;
        for (int i = 0; i < CHAN_HIDDEN1; i++) {
            yield[j] += h1[i] * (float)chan_w2[i][j] * chan_scale_w2;
        }
    }
    softmax_inplace(yield, CHAN_OUTPUT);

    return 0;
#else
    (void)query;
    /* Uniform distribution */
    for (int i = 0; i < 14; i++) yield[i] = 1.0f / 14.0f;
    return -1;
#endif
}


/* ---- Model 4: Dwell Time Optimizer ---- */

int get_dwell_time(int ap_count, int mobility_mode, float success_rate) {
#if DWELL_AVAILABLE
    /* Find AP count bucket */
    int bucket = 5;
    for (int i = 0; i < DWELL_N_BUCKETS; i++) {
        if (ap_count <= dwell_ap_buckets[i]) {
            bucket = (i > 0) ? i - 1 : 0;
            break;
        }
    }

    /* Clamp mode */
    if (mobility_mode < 0) mobility_mode = 0;
    if (mobility_mode >= DWELL_N_MODES) mobility_mode = DWELL_N_MODES - 1;

    int base = (int)dwell_table[bucket][mobility_mode];

    /* Adjust by success rate */
    float adj = 1.0f + (0.5f - clamp_f(success_rate, 0.0f, 1.0f)) * 0.5f;
    int result = (int)(base * adj * dwell_rate_factor);

    return result > 3 ? result : 3;
#else
    (void)ap_count;
    (void)mobility_mode;
    (void)success_rate;
    return 30; /* default */
#endif
}


/* ---- Model 5: Password Pattern Classifier ---- */

int predict_password_pattern(const password_query_t *query) {
#if PATTERN_AVAILABLE
    float input[PATTERN_N_FEATURES] = {
        query->vendor_category,
        query->isp_id,
        query->encryption_type,
        query->ssid_length,
        query->ssid_starts_upper,
        query->is_wpa3,
    };

    /* Layer 1 */
    float h1[PATTERN_HIDDEN1];
    for (int j = 0; j < PATTERN_HIDDEN1; j++) {
        float acc = (float)patt_b1[j] * patt_scale_b1;
        for (int i = 0; i < PATTERN_N_FEATURES; i++) {
            acc += input[i] * (float)patt_w1[i][j] * patt_scale_w1;
        }
        h1[j] = relu_f(acc);
    }

    /* Layer 2 */
    float h2[PATTERN_HIDDEN2];
    for (int j = 0; j < PATTERN_HIDDEN2; j++) {
        float acc = (float)patt_b2[j] * patt_scale_b2;
        for (int i = 0; i < PATTERN_HIDDEN1; i++) {
            acc += h1[i] * (float)patt_w2[i][j] * patt_scale_w2;
        }
        h2[j] = relu_f(acc);
    }

    /* Layer 3: softmax */
    float out[PATTERN_OUTPUT];
    for (int j = 0; j < PATTERN_OUTPUT; j++) {
        out[j] = (float)patt_b3[j] * patt_scale_b3;
        for (int i = 0; i < PATTERN_HIDDEN2; i++) {
            out[j] += h2[i] * (float)patt_w3[i][j] * patt_scale_w3;
        }
    }
    softmax_inplace(out, PATTERN_OUTPUT);

    return argmax(out, PATTERN_OUTPUT);
#else
    (void)query;
    return -1;
#endif
}


/* ---- Helpers ---- */

ap_features_t make_ap_features(const char *vendor, const char *encryption,
                                int channel, const char *ssid,
                                int clients_seen, int best_rssi,
                                int last_seen_hour) {
    ap_features_t f;

    /* Vendor category (simple string match) */
    f.vendor_category = 0.0f;
    if (vendor) {
        if (strstr(vendor, "TP-Link") || strstr(vendor, "Netgear") ||
            strstr(vendor, "D-Link") || strstr(vendor, "Linksys") ||
            strstr(vendor, "ASUS") || strstr(vendor, "Belkin") ||
            strstr(vendor, "Huawei") || strstr(vendor, "ZTE") ||
            strstr(vendor, "Technicolor") || strstr(vendor, "Arcadyan") ||
            strstr(vendor, "Sagemcom") || strstr(vendor, "Nokia") ||
            strstr(vendor, "Xiaomi") || strstr(vendor, "Tenda"))
            f.vendor_category = 1.0f;
        else if (strstr(vendor, "Cisco") || strstr(vendor, "Aruba") ||
                 strstr(vendor, "Ruckus") || strstr(vendor, "Ubiquiti") ||
                 strstr(vendor, "Meraki") || strstr(vendor, "Fortinet") ||
                 strstr(vendor, "MikroTik"))
            f.vendor_category = 2.0f;
        else if (strstr(vendor, "Espressif") || strstr(vendor, "Amazon") ||
                 strstr(vendor, "Google") || strstr(vendor, "Ring") ||
                 strstr(vendor, "Nest") || strstr(vendor, "Eero"))
            f.vendor_category = 3.0f;
    }

    /* Encryption */
    f.encryption_type = 1.0f; /* default WPA2 */
    if (encryption) {
        if (strstr(encryption, "WPA3")) f.encryption_type = 2.0f;
        else if (strstr(encryption, "WPA")) f.encryption_type = 1.0f;
        else if (strstr(encryption, "WEP")) f.encryption_type = 0.0f;
        else if (strstr(encryption, "OPEN") || strstr(encryption, "OPN"))
            f.encryption_type = -1.0f;
    }

    /* Channel — dual-band normalization matching training pipeline */
    if (channel > 14) {
        /* 5GHz: map ch 36-165 to [0.5, 1.0] */
        f.channel_norm = clamp_f(0.5f + (float)(channel - 36) / 258.0f, 0.5f, 1.0f);
    } else {
        /* 2.4GHz: ch/14 */
        f.channel_norm = clamp_f((float)channel / 14.0f, 0.0f, 0.5f);
    }

    /* Beacon / hidden SSID */
    f.beacon_flag = (ssid && ssid[0] != '\0') ? 0.0f : 2.0f;

    /* Client count */
    f.client_count_log = logf((float)(clients_seen + 1));

    /* RSSI */
    f.rssi_norm = clamp_f(((float)best_rssi + 100.0f) / 60.0f, 0.0f, 1.0f);

    /* Time of day */
    f.time_of_day = clamp_f((float)last_seen_hour / 24.0f, 0.0f, 1.0f);

    return f;
}


int model_get_version(void) {
    return MODEL_VERSION;
}


int model_is_available(int model_id) {
    switch (model_id) {
#if VULN_AVAILABLE
        case 1: return 1;
#endif
#if PHASE_AVAILABLE
        case 2: return 1;
#endif
#if CHAN_AVAILABLE
        case 3: return 1;
#endif
#if DWELL_AVAILABLE
        case 4: return 1;
#endif
#if PATTERN_AVAILABLE
        case 5: return 1;
#endif
        default: return 0;
    }
}
